#!/bin/sh /etc/rc.common

START=91
STOP=91

start() {
	echo 'Getting PyAudio'
	python3 -c "import pyaudio"
	if [ "$?" -ne 0 ] 
	then
		cd /usr/lib/
		ln -s libportaudio.so.2.0.0 libportaudio.so
		cd /root/aud/PyAudio-0.2.11/
		python3 setup.py build
		python3 setup.py install
	else
		echo 'Already installed' > /root/aud/exists.txt
	fi

}
stop() {
	echo "PyAudio OFF"
}
